#!/usr/bin/env bash
# Regenerates the sudo-kernel-derived host adapters for both consumers of
# sudo/craft.sudo: the Python CLI (src/infinite_craft_cli/_sudo/) and the
# JS bookmarklet (bookmarklet/_sudo/). Safe to re-run at any time — it wipes
# and rebuilds both output directories from sudo/craft.sudo.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUDOC_BIN="${SUDOC_BIN:-/Users/zachmills/Documents/Projects/sudocode/sudoc/target/release/sudoc}"

if [ ! -x "$SUDOC_BIN" ]; then
    echo "error: sudoc binary not found or not executable at: $SUDOC_BIN" >&2
    echo "Build it first: (cd /Users/zachmills/Documents/Projects/sudocode/sudoc && cargo build --release)" >&2
    echo "Or point SUDOC_BIN at an existing build before re-running this script." >&2
    exit 1
fi

PY_OUT="$REPO_ROOT/src/infinite_craft_cli/_sudo"
JS_OUT="$REPO_ROOT/bookmarklet/_sudo"
SRC="$REPO_ROOT/sudo/craft.sudo"

rm -rf "$PY_OUT" "$JS_OUT"
mkdir -p "$PY_OUT" "$JS_OUT"

echo "Generating Python target -> $PY_OUT"
"$SUDOC_BIN" build --target py -o "$PY_OUT" "$SRC"

echo "Generating JS target -> $JS_OUT"
"$SUDOC_BIN" build --target js -o "$JS_OUT" "$SRC"

# sudoc's generated Python modules import each other via bare, top-level
# module names (e.g. `import _craft_impl as _impl`), which only resolve if
# this directory is itself on sys.path. Write a small __init__.py (not
# produced by sudoc) that adds its own directory to sys.path before
# importing the host-facing adapter module, so
# `from infinite_craft_cli._sudo import craft` works regardless of how the
# _sudo package itself was imported.
cat > "$PY_OUT/__init__.py" << 'PYEOF'
"""Generated by scripts/generate.sh — DO NOT EDIT BY HAND.

sudoc's generated Python modules (craft.py, _craft_impl.py, _sudo_rt.py,
_strings_impl.py) import each other via bare top-level module names, which
only resolve when this directory is on sys.path. This shim adds it before
importing the host-facing adapter module.
"""
import os
import sys

_here = os.path.dirname(__file__)
if _here not in sys.path:
    sys.path.insert(0, _here)

from . import craft  # noqa: E402,F401
PYEOF

echo "Done."
