// Generated by sudoc from regex.sudo — do not edit; edit the sudo source.
import * as _rt from "./_sudo_rt.mjs";
import * as strings from "./_strings_impl.mjs";

export class CompiledPattern {
    static _sudoKind = ["r", "CompiledPattern"];
    static _sudoFields = ["states", "start"];
    constructor(states, start) {
        this.states = states;
        this.start = start;
    }
}

export class Item {
    static _sudoKind = ["r", "Item"];
    static _sudoFields = ["atom", "quant"];
    constructor(atom, quant) {
        this.atom = atom;
        this.quant = quant;
    }
}

export class BraceQuant {
    static _sudoKind = ["r", "BraceQuant"];
    static _sudoFields = ["kind", "m", "n", "end"];
    constructor(kind, m, n, end) {
        this.kind = kind;
        this.m = m;
        this.n = n;
        this.end = end;
    }
}

export class Branch {
    static _sudoKind = ["r", "Branch"];
    static _sudoFields = ["items"];
    constructor(items) {
        this.items = items;
    }
}

export class ParseResult {
    static _sudoKind = ["r", "ParseResult"];
    static _sudoFields = ["branches"];
    constructor(branches) {
        this.branches = branches;
    }
}

export class Sudo_10AssertKind_5Start {
    static _sudoKind = ["e", "AssertKind.Start"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_10AssertKind_3End {
    static _sudoKind = ["e", "AssertKind.End"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_10AssertKind_12WordBoundary {
    static _sudoKind = ["e", "AssertKind.WordBoundary"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_10AssertKind_15NotWordBoundary {
    static _sudoKind = ["e", "AssertKind.NotWordBoundary"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_8NfaState_7CharLit {
    static _sudoKind = ["e", "NfaState.CharLit"];
    static _sudoFields = ["ch", "out"];
    constructor(ch, out) {
        this.ch = ch;
        this.out = out;
    }
}

export class Sudo_8NfaState_9CharClass {
    static _sudoKind = ["e", "NfaState.CharClass"];
    static _sudoFields = ["negate", "ranges", "out"];
    constructor(negate, ranges, out) {
        this.negate = negate;
        this.ranges = ranges;
        this.out = out;
    }
}

export class Sudo_8NfaState_5Split {
    static _sudoKind = ["e", "NfaState.Split"];
    static _sudoFields = ["out1", "out2"];
    constructor(out1, out2) {
        this.out1 = out1;
        this.out2 = out2;
    }
}

export class Sudo_8NfaState_6Assert {
    static _sudoKind = ["e", "NfaState.Assert"];
    static _sudoFields = ["kind", "out"];
    constructor(kind, out) {
        this.kind = kind;
        this.out = out;
    }
}

export class Sudo_8NfaState_5Match {
    static _sudoKind = ["e", "NfaState.Match"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_4Atom_3Lit {
    static _sudoKind = ["e", "Atom.Lit"];
    static _sudoFields = ["ch"];
    constructor(ch) {
        this.ch = ch;
    }
}

export class Sudo_4Atom_8Wildcard {
    static _sudoKind = ["e", "Atom.Wildcard"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_4Atom_5Class {
    static _sudoKind = ["e", "Atom.Class"];
    static _sudoFields = ["negate", "ranges"];
    constructor(negate, ranges) {
        this.negate = negate;
        this.ranges = ranges;
    }
}

export class Sudo_4Atom_9Assertion {
    static _sudoKind = ["e", "Atom.Assertion"];
    static _sudoFields = ["kind"];
    constructor(kind) {
        this.kind = kind;
    }
}

export class Sudo_4Atom_5Group {
    static _sudoKind = ["e", "Atom.Group"];
    static _sudoFields = ["branches"];
    constructor(branches) {
        this.branches = branches;
    }
}

export class Sudo_5Quant_4Once {
    static _sudoKind = ["e", "Quant.Once"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_5Quant_4Star {
    static _sudoKind = ["e", "Quant.Star"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_5Quant_4Plus {
    static _sudoKind = ["e", "Quant.Plus"];
    static _sudoFields = [];
    constructor() {
    }
}

export class Sudo_5Quant_3Opt {
    static _sudoKind = ["e", "Quant.Opt"];
    static _sudoFields = [];
    constructor() {
    }
}

export const max_nfa_states = 100000n;

export function fold_ascii(c) {
    if (c >= 65n && c <= 90n) {
        return _rt.chk(c + 32n);
    }
    return c;
}

export function swap_case(c) {
    if (c >= 65n && c <= 90n) {
        return _rt.chk(c + 32n);
    }
    if (c >= 97n && c <= 122n) {
        return _rt.chk(c - 32n);
    }
    return c;
}

export function ci_eq(a, b, ignore_case) {
    if (ignore_case) {
        return fold_ascii(a) === fold_ascii(b);
    }
    return a === b;
}

export function in_ranges(ranges, c) {
    for (const r of ranges.slice()) {
        let lo;
        let hi;
        [lo, hi] = r;
        if (c >= lo && c <= hi) {
            return true;
        }
    }
    return false;
}

export function class_matches(negate, ranges, c, ignore_case) {
    let m = in_ranges(ranges, c);
    if (ignore_case) {
        let alt = swap_case(c);
        if (alt !== c && in_ranges(ranges, alt)) {
            m = true;
        }
    }
    if (negate) {
        return !m;
    }
    return m;
}

export function parse_class_body(pattern, open_at, caret_negates, validate_ranges, allow_escapes) {
    let i = _rt.chk(open_at + 1n);
    if (i >= globalThis.BigInt(pattern.length)) {
        return new _rt.Err(_rt.txt("invalid pattern: unclosed character class"));
    }
    let negate = false;
    let is_caret_neg = caret_negates && _rt.at(pattern, i) === 94n;
    if (_rt.at(pattern, i) === 33n) {
        negate = true;
        i = _rt.chk(i + 1n);
    } else if (is_caret_neg) {
        negate = true;
        i = _rt.chk(i + 1n);
    }
    let ranges = _rt.lst([]);
    if (i < globalThis.BigInt(pattern.length) && _rt.at(pattern, i) === 93n) {
        ranges.push([93n, 93n]);
        i = _rt.chk(i + 1n);
    }
    while (i < globalThis.BigInt(pattern.length)) {
        if (allow_escapes && _rt.at(pattern, i) === 92n) {
            if (_rt.chk(i + 1n) >= globalThis.BigInt(pattern.length)) {
                return new _rt.Err(_rt.txt("invalid pattern: unclosed character class"));
            }
            let e = _rt.at(pattern, _rt.chk(i + 1n));
            if (e === 100n) {
                ranges.push([48n, 57n]);
                i = _rt.chk(i + 2n);
                continue;
            }
            if (e === 119n) {
                ranges.push([65n, 90n]);
                ranges.push([97n, 122n]);
                ranges.push([48n, 57n]);
                ranges.push([95n, 95n]);
                i = _rt.chk(i + 2n);
                continue;
            }
            if (e === 115n) {
                ranges.push([32n, 32n]);
                ranges.push([9n, 9n]);
                ranges.push([10n, 10n]);
                ranges.push([13n, 13n]);
                ranges.push([12n, 12n]);
                ranges.push([11n, 11n]);
                i = _rt.chk(i + 2n);
                continue;
            }
            if (e === 98n) {
                ranges.push([8n, 8n]);
                i = _rt.chk(i + 2n);
                continue;
            }
            if (e === 68n || e === 87n || e === 83n) {
                let msgc = _rt.txt("invalid pattern: unsupported escape \\");
                msgc.push(e);
                msgc = _rt.dup(msgc.concat(_rt.txt(" inside character class")));
                return new _rt.Err(_rt.dup(msgc));
            }
            if (e === 46n || e === 42n || e === 43n || e === 63n || e === 91n || e === 93n || e === 94n || e === 36n || e === 124n || e === 92n || e === 47n || e === 123n || e === 125n || e === 40n || e === 41n || e === 45n) {
                ranges.push([e, e]);
                i = _rt.chk(i + 2n);
                continue;
            }
            let msgu = _rt.txt("invalid pattern: unsupported escape \\");
            msgu.push(e);
            return new _rt.Err(_rt.dup(msgu));
        }
        if (_rt.at(pattern, i) === 93n) {
            return new _rt.Ok([negate, _rt.dup(ranges), _rt.chk(i + 1n)]);
        }
        let lo = _rt.at(pattern, i);
        i = _rt.chk(i + 1n);
        if (i < globalThis.BigInt(pattern.length) && _rt.at(pattern, i) === 45n && _rt.chk(i + 1n) < globalThis.BigInt(pattern.length) && _rt.at(pattern, _rt.chk(i + 1n)) !== 93n) {
            let hi = _rt.at(pattern, _rt.chk(i + 1n));
            i = _rt.chk(i + 2n);
            if (validate_ranges && lo > hi) {
                return new _rt.Err(_rt.txt("invalid pattern: bad character range"));
            }
            ranges.push([lo, hi]);
        } else {
            ranges.push([lo, lo]);
        }
    }
    return new _rt.Err(_rt.txt("invalid pattern: unclosed character class"));
}

export function is_digit(c) {
    return c >= 48n && c <= 57n;
}

export function parse_uint_at(pattern, i) {
    if (i >= globalThis.BigInt(pattern.length) || !is_digit(_rt.at(pattern, i))) {
        return _rt.NONE;
    }
    let v = 0n;
    let j = i;
    while (j < globalThis.BigInt(pattern.length) && is_digit(_rt.at(pattern, j))) {
        let d = _rt.chk(_rt.at(pattern, j) - 48n);
        if (v > 100000n) {
            v = 100000n;
        } else {
            v = _rt.chk(_rt.chk(v * 10n) + d);
        }
        j = _rt.chk(j + 1n);
    }
    return new _rt.Some([v, j]);
}

export function try_parse_brace(pattern, i) {
    if (i >= globalThis.BigInt(pattern.length) || _rt.at(pattern, i) !== 123n) {
        return _rt.NONE;
    }
    let j = _rt.chk(i + 1n);
    let m_opt = parse_uint_at(pattern, j);
    if (_rt.is_none(m_opt)) {
        return _rt.NONE;
    }
    let m;
    [m, j] = _rt.unwrap(m_opt);
    if (j >= globalThis.BigInt(pattern.length)) {
        return _rt.NONE;
    }
    if (_rt.at(pattern, j) === 125n) {
        return new _rt.Some(_rt.rec(new BraceQuant(0n, m, m, _rt.chk(j + 1n))));
    }
    if (_rt.at(pattern, j) !== 44n) {
        return _rt.NONE;
    }
    j = _rt.chk(j + 1n);
    if (j >= globalThis.BigInt(pattern.length)) {
        return _rt.NONE;
    }
    if (_rt.at(pattern, j) === 125n) {
        return new _rt.Some(_rt.rec(new BraceQuant(1n, m, 0n, _rt.chk(j + 1n))));
    }
    let n_opt = parse_uint_at(pattern, j);
    if (_rt.is_none(n_opt)) {
        return _rt.NONE;
    }
    let n;
    [n, j] = _rt.unwrap(n_opt);
    if (j >= globalThis.BigInt(pattern.length) || _rt.at(pattern, j) !== 125n) {
        return _rt.NONE;
    }
    return new _rt.Some(_rt.rec(new BraceQuant(2n, m, n, _rt.chk(j + 1n))));
}

export function err_bound_cap() {
    return _rt.txt("invalid pattern: quantifier bound exceeds 1000");
}

export function err_bound_order() {
    return _rt.txt("invalid pattern: quantifier range min greater than max");
}

export function err_nothing_to_repeat() {
    return _rt.txt("invalid pattern: quantifier with nothing to repeat");
}

export function err_size_budget() {
    return _rt.txt("invalid pattern: exceeds max_nfa_states budget (100000); pattern too large");
}

export function atom_weight(atom) {
    {
        const _sudo_sc = atom;
        if (_sudo_sc instanceof Sudo_4Atom_3Lit) {
            const ch = _sudo_sc.ch;
            return 1n;
        } else if (_sudo_sc instanceof Sudo_4Atom_8Wildcard) {
            return 1n;
        } else if (_sudo_sc instanceof Sudo_4Atom_5Class) {
            const negate = _sudo_sc.negate;
            const ranges = _rt.dup(_sudo_sc.ranges);
            return 1n;
        } else if (_sudo_sc instanceof Sudo_4Atom_9Assertion) {
            const kind = _sudo_sc.kind;
            return 1n;
        } else if (_sudo_sc instanceof Sudo_4Atom_5Group) {
            const branches = _rt.dup(_sudo_sc.branches);
            let total = 1n;
            for (const br of branches.slice()) {
                for (const it of br.slice()) {
                    total = _rt.chk(total + atom_weight(it.atom));
                }
            }
            return total;
        }
    }
}

export function append_copies(items, atom, quant, count, budget) {
    let w = atom_weight(atom);
    let cost = _rt.chk(w * count);
    if (cost > budget) {
        return [new _rt.Err(err_size_budget()), items, budget];
    }
    budget = _rt.chk(budget - cost);
    {
        const _sudo_from_k = 1n;
        const _sudo_to_k = count;
        for (let k = _sudo_from_k; k <= _sudo_to_k; k += 1n) {
            items.push(_rt.rec(new Item(atom, quant)));
        }
    }
    return [new _rt.Ok(true), items, budget];
}

export function expand_brace(items, atom, bq, budget) {
    let m = bq.m;
    let n = bq.n;
    if (m > 1000n) {
        return [new _rt.Err(err_bound_cap()), items, budget];
    }
    if (bq.kind === 0n) {
        let _sudo_h0;
        [_sudo_h0, items, budget] = append_copies(items, atom, new Sudo_5Quant_4Once(), m, budget);
        return [_sudo_h0, items, budget];
    }
    if (bq.kind === 1n) {
        let r1;
        [r1, items, budget] = append_copies(items, atom, new Sudo_5Quant_4Once(), m, budget);
        {
            const _sudo_sc = r1;
            if (_sudo_sc instanceof _rt.Err) {
                const e1 = _sudo_sc.error;
                return [new _rt.Err(_rt.dup(e1)), items, budget];
            } else if (_sudo_sc instanceof _rt.Ok) {
                const v1 = _sudo_sc.value;
                _rt.sudo_assert_eq(v1, v1, 425);
            }
        }
        let _sudo_h1;
        [_sudo_h1, items, budget] = append_copies(items, atom, new Sudo_5Quant_4Star(), 1n, budget);
        return [_sudo_h1, items, budget];
    }
    if (n > 1000n) {
        return [new _rt.Err(err_bound_cap()), items, budget];
    }
    if (m > n) {
        return [new _rt.Err(err_bound_order()), items, budget];
    }
    let r2;
    [r2, items, budget] = append_copies(items, atom, new Sudo_5Quant_4Once(), m, budget);
    {
        const _sudo_sc = r2;
        if (_sudo_sc instanceof _rt.Err) {
            const e2 = _sudo_sc.error;
            return [new _rt.Err(_rt.dup(e2)), items, budget];
        } else if (_sudo_sc instanceof _rt.Ok) {
            const v2 = _sudo_sc.value;
            _rt.sudo_assert_eq(v2, v2, 437);
        }
    }
    let _sudo_h2;
    [_sudo_h2, items, budget] = append_copies(items, atom, new Sudo_5Quant_3Opt(), _rt.chk(n - m), budget);
    return [_sudo_h2, items, budget];
}

export function parse_branch_items(pattern, start_i, end_i, is_glob, budget) {
    let items = _rt.lst([]);
    let i = start_i;
    while (i < end_i) {
        let ch = _rt.at(pattern, i);
        if (is_glob) {
            if (ch === 42n) {
                let empty_r = _rt.lst([]);
                items.push(_rt.rec(new Item(new Sudo_4Atom_5Class(true, _rt.dup(empty_r)), new Sudo_5Quant_4Star())));
                i = _rt.chk(i + 1n);
                continue;
            }
            if (ch === 63n) {
                let empty_r2 = _rt.lst([]);
                items.push(_rt.rec(new Item(new Sudo_4Atom_5Class(true, _rt.dup(empty_r2)), new Sudo_5Quant_4Once())));
                i = _rt.chk(i + 1n);
                continue;
            }
            if (ch === 91n) {
                let cr = parse_class_body(pattern, i, false, false, false);
                if (_rt.is_ok(cr)) {
                    let triple = _rt.dup(_rt.unwrap(cr));
                    let neg;
                    let rng;
                    let ni;
                    [neg, rng, ni] = triple;
                    items.push(_rt.rec(new Item(new Sudo_4Atom_5Class(neg, _rt.dup(rng)), new Sudo_5Quant_4Once())));
                    i = ni;
                } else {
                    items.push(_rt.rec(new Item(new Sudo_4Atom_3Lit(91n), new Sudo_5Quant_4Once())));
                    i = _rt.chk(i + 1n);
                }
                continue;
            }
            items.push(_rt.rec(new Item(new Sudo_4Atom_3Lit(ch), new Sudo_5Quant_4Once())));
            i = _rt.chk(i + 1n);
            continue;
        }
        if (ch === 42n || ch === 43n || ch === 63n) {
            return [new _rt.Err(err_nothing_to_repeat()), budget];
        }
        if (ch === 123n) {
            let bq_opt = try_parse_brace(pattern, i);
            if (_rt.is_some(bq_opt)) {
                return [new _rt.Err(err_nothing_to_repeat()), budget];
            }
            items.push(_rt.rec(new Item(new Sudo_4Atom_3Lit(123n), new Sudo_5Quant_4Once())));
            i = _rt.chk(i + 1n);
            continue;
        }
        if (ch === 41n) {
            return [new _rt.Err(_rt.txt("invalid pattern: unmatched ')' in pattern")), budget];
        }
        let atom = new Sudo_4Atom_3Lit(ch);
        let atom_end = _rt.chk(i + 1n);
        if (ch === 46n) {
            atom = new Sudo_4Atom_8Wildcard();
            atom_end = _rt.chk(i + 1n);
        } else if (ch === 91n) {
            let cr2 = parse_class_body(pattern, i, true, true, true);
            {
                const _sudo_sc = cr2;
                if (_sudo_sc instanceof _rt.Ok) {
                    const triple2 = _sudo_sc.value;
                    let neg2;
                    let rng2;
                    let ni2;
                    [neg2, rng2, ni2] = triple2;
                    atom = new Sudo_4Atom_5Class(neg2, _rt.dup(rng2));
                    atom_end = ni2;
                } else if (_sudo_sc instanceof _rt.Err) {
                    const emsg = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(emsg)), budget];
                }
            }
        } else if (ch === 92n) {
            let esc_r = parse_escape(pattern, i);
            {
                const _sudo_sc = esc_r;
                if (_sudo_sc instanceof _rt.Ok) {
                    const pair = _sudo_sc.value;
                    let eatom;
                    let ni3;
                    [eatom, ni3] = pair;
                    atom = eatom;
                    atom_end = ni3;
                } else if (_sudo_sc instanceof _rt.Err) {
                    const emsg2 = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(emsg2)), budget];
                }
            }
        } else if (ch === 94n) {
            atom = new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_5Start());
            atom_end = _rt.chk(i + 1n);
        } else if (ch === 36n) {
            atom = new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_3End());
            atom_end = _rt.chk(i + 1n);
        } else if (ch === 40n) {
            let close_r = find_matching_paren(pattern, i, end_i);
            {
                const _sudo_sc = close_r;
                if (_sudo_sc instanceof _rt.Err) {
                    const emsg_p = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(emsg_p)), budget];
                } else if (_sudo_sc instanceof _rt.Ok) {
                    const close = _sudo_sc.value;
                    let body_spans = find_pipe_spans(pattern, _rt.chk(i + 1n), close);
                    let g_branches = _rt.lst([]);
                    for (const bspan of body_spans.slice()) {
                        let bs0;
                        let be0;
                        [bs0, be0] = bspan;
                        let sub_r;
                        [sub_r, budget] = parse_branch_items(pattern, bs0, be0, false, budget);
                        {
                            const _sudo_sc = sub_r;
                            if (_sudo_sc instanceof _rt.Ok) {
                                const sub_items = _sudo_sc.value;
                                g_branches.push(_rt.dup(sub_items));
                            } else if (_sudo_sc instanceof _rt.Err) {
                                const emsg_g = _sudo_sc.error;
                                return [new _rt.Err(_rt.dup(emsg_g)), budget];
                            }
                        }
                    }
                    atom = new Sudo_4Atom_5Group(_rt.dup(g_branches));
                    atom_end = _rt.chk(close + 1n);
                }
            }
        } else {
            atom = new Sudo_4Atom_3Lit(ch);
            atom_end = _rt.chk(i + 1n);
        }
        i = atom_end;
        if (i < end_i) {
            let qch = _rt.at(pattern, i);
            if (qch === 42n) {
                items.push(_rt.rec(new Item(atom, new Sudo_5Quant_4Star())));
                i = _rt.chk(i + 1n);
            } else if (qch === 43n) {
                items.push(_rt.rec(new Item(atom, new Sudo_5Quant_4Plus())));
                i = _rt.chk(i + 1n);
            } else if (qch === 63n) {
                items.push(_rt.rec(new Item(atom, new Sudo_5Quant_3Opt())));
                i = _rt.chk(i + 1n);
            } else if (qch === 123n) {
                let bq2 = try_parse_brace(pattern, i);
                if (_rt.is_some(bq2)) {
                    let bq = _rt.dup(_rt.unwrap(bq2));
                    let er;
                    [er, items, budget] = expand_brace(items, atom, bq, budget);
                    {
                        const _sudo_sc = er;
                        if (_sudo_sc instanceof _rt.Ok) {
                            const okv = _sudo_sc.value;
                            _rt.sudo_assert_eq(okv, okv, 572);
                            i = bq.end;
                        } else if (_sudo_sc instanceof _rt.Err) {
                            const em = _sudo_sc.error;
                            return [new _rt.Err(_rt.dup(em)), budget];
                        }
                    }
                } else {
                    items.push(_rt.rec(new Item(atom, new Sudo_5Quant_4Once())));
                }
            } else {
                items.push(_rt.rec(new Item(atom, new Sudo_5Quant_4Once())));
            }
        } else {
            items.push(_rt.rec(new Item(atom, new Sudo_5Quant_4Once())));
        }
    }
    return [new _rt.Ok(_rt.dup(items)), budget];
}

export function parse_escape(pattern, i) {
    if (_rt.chk(i + 1n) >= globalThis.BigInt(pattern.length)) {
        return new _rt.Err(_rt.txt("invalid pattern: trailing backslash"));
    }
    let e = _rt.at(pattern, _rt.chk(i + 1n));
    let ni = _rt.chk(i + 2n);
    if (e === 46n || e === 42n || e === 43n || e === 63n || e === 91n || e === 93n || e === 94n || e === 36n || e === 124n || e === 92n || e === 47n || e === 123n || e === 125n || e === 40n || e === 41n) {
        return new _rt.Ok([new Sudo_4Atom_3Lit(e), ni]);
    }
    if (e === 100n) {
        let r = _rt.lst([[48n, 57n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(false, _rt.dup(r)), ni]);
    }
    if (e === 68n) {
        let r2 = _rt.lst([[48n, 57n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(true, _rt.dup(r2)), ni]);
    }
    if (e === 119n) {
        let r3 = _rt.lst([[65n, 90n], [97n, 122n], [48n, 57n], [95n, 95n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(false, _rt.dup(r3)), ni]);
    }
    if (e === 87n) {
        let r4 = _rt.lst([[65n, 90n], [97n, 122n], [48n, 57n], [95n, 95n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(true, _rt.dup(r4)), ni]);
    }
    if (e === 115n) {
        let r5 = _rt.lst([[32n, 32n], [9n, 9n], [10n, 10n], [13n, 13n], [12n, 12n], [11n, 11n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(false, _rt.dup(r5)), ni]);
    }
    if (e === 83n) {
        let r6 = _rt.lst([[32n, 32n], [9n, 9n], [10n, 10n], [13n, 13n], [12n, 12n], [11n, 11n]]);
        return new _rt.Ok([new Sudo_4Atom_5Class(true, _rt.dup(r6)), ni]);
    }
    if (e === 98n) {
        return new _rt.Ok([new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_12WordBoundary()), ni]);
    }
    if (e === 66n) {
        return new _rt.Ok([new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_15NotWordBoundary()), ni]);
    }
    let msgu2 = _rt.txt("invalid pattern: unsupported escape \\");
    msgu2.push(e);
    return new _rt.Err(_rt.dup(msgu2));
}

export function find_pipe_spans(pattern, start, end) {
    let spans = _rt.lst([]);
    let seg_start = start;
    let i = start;
    let depth = 0n;
    while (i < end) {
        let ch = _rt.at(pattern, i);
        if (ch === 92n) {
            if (_rt.chk(i + 1n) < end) {
                i = _rt.chk(i + 2n);
            } else {
                i = _rt.chk(i + 1n);
            }
            continue;
        }
        if (ch === 91n) {
            let cr = parse_class_body(pattern, i, true, false, true);
            if (_rt.is_ok(cr)) {
                let triple = _rt.dup(_rt.unwrap(cr));
                let neg;
                let rng;
                let ni;
                [neg, rng, ni] = triple;
                i = ni;
                continue;
            } else {
                i = _rt.chk(i + 1n);
                continue;
            }
        }
        if (ch === 40n) {
            depth = _rt.chk(depth + 1n);
            i = _rt.chk(i + 1n);
            continue;
        }
        if (ch === 41n) {
            if (depth > 0n) {
                depth = _rt.chk(depth - 1n);
            }
            i = _rt.chk(i + 1n);
            continue;
        }
        if (ch === 124n && depth === 0n) {
            spans.push([seg_start, i]);
            seg_start = _rt.chk(i + 1n);
            i = _rt.chk(i + 1n);
            continue;
        }
        i = _rt.chk(i + 1n);
    }
    spans.push([seg_start, end]);
    return _rt.dup(spans);
}

export function find_top_level_pipe_spans(pattern) {
    return find_pipe_spans(pattern, 0n, globalThis.BigInt(pattern.length));
}

export function find_matching_paren(pattern, open_i, end_i) {
    let i = _rt.chk(open_i + 1n);
    let depth = 1n;
    while (i < end_i) {
        let ch = _rt.at(pattern, i);
        if (ch === 92n) {
            if (_rt.chk(i + 1n) < end_i) {
                i = _rt.chk(i + 2n);
            } else {
                i = _rt.chk(i + 1n);
            }
            continue;
        }
        if (ch === 91n) {
            let cr = parse_class_body(pattern, i, true, false, true);
            if (_rt.is_ok(cr)) {
                let triple = _rt.dup(_rt.unwrap(cr));
                let neg;
                let rng;
                let ni;
                [neg, rng, ni] = triple;
                i = ni;
                continue;
            } else {
                i = _rt.chk(i + 1n);
                continue;
            }
        }
        if (ch === 40n) {
            depth = _rt.chk(depth + 1n);
            i = _rt.chk(i + 1n);
            continue;
        }
        if (ch === 41n) {
            depth = _rt.chk(depth - 1n);
            if (depth === 0n) {
                return new _rt.Ok(i);
            }
            i = _rt.chk(i + 1n);
            continue;
        }
        i = _rt.chk(i + 1n);
    }
    return new _rt.Err(_rt.txt("invalid pattern: unmatched '(' in pattern"));
}

export function parse_pattern(pattern, is_glob, budget) {
    if (is_glob) {
        let items_r;
        [items_r, budget] = parse_branch_items(pattern, 0n, globalThis.BigInt(pattern.length), true, budget);
        {
            const _sudo_sc = items_r;
            if (_sudo_sc instanceof _rt.Ok) {
                const items = _sudo_sc.value;
                let wrapped = _rt.lst([_rt.rec(new Item(new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_5Start()), new Sudo_5Quant_4Once()))]);
                for (const it of items.slice()) {
                    wrapped.push(_rt.dup(it));
                }
                wrapped.push(_rt.rec(new Item(new Sudo_4Atom_9Assertion(new Sudo_10AssertKind_3End()), new Sudo_5Quant_4Once())));
                let only_branch = _rt.rec(new Branch(_rt.dup(wrapped)));
                let only = _rt.lst([_rt.dup(only_branch)]);
                return [new _rt.Ok(_rt.rec(new ParseResult(_rt.dup(only)))), budget];
            } else if (_sudo_sc instanceof _rt.Err) {
                const msg = _sudo_sc.error;
                return [new _rt.Err(_rt.dup(msg)), budget];
            }
        }
    }
    let spans = find_top_level_pipe_spans(pattern);
    let branches = _rt.lst([]);
    for (const span of spans.slice()) {
        let s0;
        let e0;
        [s0, e0] = span;
        let items_r;
        [items_r, budget] = parse_branch_items(pattern, s0, e0, false, budget);
        {
            const _sudo_sc = items_r;
            if (_sudo_sc instanceof _rt.Ok) {
                const items = _sudo_sc.value;
                branches.push(_rt.rec(new Branch(_rt.dup(items))));
            } else if (_sudo_sc instanceof _rt.Err) {
                const msg = _sudo_sc.error;
                return [new _rt.Err(_rt.dup(msg)), budget];
            }
        }
    }
    return [new _rt.Ok(_rt.rec(new ParseResult(_rt.dup(branches)))), budget];
}

export function build_group_fragment(branches, out_index, states, budget) {
    let branch_starts = _rt.lst([]);
    for (const br_items of branches.slice()) {
        let next_index = out_index;
        let k = _rt.chk(globalThis.BigInt(br_items.length) - 1n);
        while (k >= 0n) {
            let r;
            [r, states, budget] = build_fragment(_rt.at(br_items, k), next_index, states, budget);
            {
                const _sudo_sc = r;
                if (_sudo_sc instanceof _rt.Ok) {
                    const idx = _sudo_sc.value;
                    next_index = idx;
                } else if (_sudo_sc instanceof _rt.Err) {
                    const e = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(e)), states, budget];
                }
            }
            k = _rt.chk(k - 1n);
        }
        branch_starts.push(next_index);
    }
    if (globalThis.BigInt(branch_starts.length) === 0n) {
        return [new _rt.Ok(out_index), states, budget];
    }
    if (globalThis.BigInt(branch_starts.length) === 1n) {
        return [new _rt.Ok(_rt.at(branch_starts, 0n)), states, budget];
    }
    let cur = _rt.at(branch_starts, _rt.chk(globalThis.BigInt(branch_starts.length) - 1n));
    let j = _rt.chk(globalThis.BigInt(branch_starts.length) - 2n);
    while (j >= 0n) {
        if (budget <= 0n) {
            return [new _rt.Err(err_size_budget()), states, budget];
        }
        budget = _rt.chk(budget - 1n);
        states.push(new Sudo_8NfaState_5Split(_rt.at(branch_starts, j), cur));
        cur = _rt.chk(globalThis.BigInt(states.length) - 1n);
        j = _rt.chk(j - 1n);
    }
    return [new _rt.Ok(cur), states, budget];
}

export function build_atom_fragment(atom, out_index, states, budget) {
    {
        const _sudo_sc = atom;
        if (_sudo_sc instanceof Sudo_4Atom_3Lit) {
            const ch = _sudo_sc.ch;
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            states.push(new Sudo_8NfaState_7CharLit(ch, out_index));
            return [new _rt.Ok(_rt.chk(globalThis.BigInt(states.length) - 1n)), states, budget];
        } else if (_sudo_sc instanceof Sudo_4Atom_8Wildcard) {
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            let nl = _rt.lst([[10n, 10n]]);
            states.push(new Sudo_8NfaState_9CharClass(true, _rt.dup(nl), out_index));
            return [new _rt.Ok(_rt.chk(globalThis.BigInt(states.length) - 1n)), states, budget];
        } else if (_sudo_sc instanceof Sudo_4Atom_5Class) {
            const negate = _sudo_sc.negate;
            const ranges = _rt.dup(_sudo_sc.ranges);
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            states.push(new Sudo_8NfaState_9CharClass(negate, _rt.dup(ranges), out_index));
            return [new _rt.Ok(_rt.chk(globalThis.BigInt(states.length) - 1n)), states, budget];
        } else if (_sudo_sc instanceof Sudo_4Atom_9Assertion) {
            const kind = _sudo_sc.kind;
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            states.push(new Sudo_8NfaState_6Assert(kind, out_index));
            return [new _rt.Ok(_rt.chk(globalThis.BigInt(states.length) - 1n)), states, budget];
        } else if (_sudo_sc instanceof Sudo_4Atom_5Group) {
            const branches = _rt.dup(_sudo_sc.branches);
            let _sudo_h0;
            [_sudo_h0, states, budget] = build_group_fragment(branches, out_index, states, budget);
            return [_sudo_h0, states, budget];
        }
    }
}

export function build_fragment(item, out_index, states, budget) {
    {
        const _sudo_sc = item.quant;
        if (_sudo_sc instanceof Sudo_5Quant_4Once) {
            let _sudo_h0;
            [_sudo_h0, states, budget] = build_atom_fragment(item.atom, out_index, states, budget);
            return [_sudo_h0, states, budget];
        } else if (_sudo_sc instanceof Sudo_5Quant_3Opt) {
            let r;
            [r, states, budget] = build_atom_fragment(item.atom, out_index, states, budget);
            {
                const _sudo_sc = r;
                if (_sudo_sc instanceof _rt.Err) {
                    const e = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(e)), states, budget];
                } else if (_sudo_sc instanceof _rt.Ok) {
                    const atom_idx = _sudo_sc.value;
                    if (budget <= 0n) {
                        return [new _rt.Err(err_size_budget()), states, budget];
                    }
                    budget = _rt.chk(budget - 1n);
                    states.push(new Sudo_8NfaState_5Split(atom_idx, out_index));
                    return [new _rt.Ok(_rt.chk(globalThis.BigInt(states.length) - 1n)), states, budget];
                }
            }
        } else if (_sudo_sc instanceof Sudo_5Quant_4Star) {
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            let split_idx = globalThis.BigInt(states.length);
            states.push(new Sudo_8NfaState_5Match());
            let r2;
            [r2, states, budget] = build_atom_fragment(item.atom, split_idx, states, budget);
            {
                const _sudo_sc = r2;
                if (_sudo_sc instanceof _rt.Err) {
                    const e2 = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(e2)), states, budget];
                } else if (_sudo_sc instanceof _rt.Ok) {
                    const atom_idx2 = _sudo_sc.value;
                    _rt.put(states, split_idx, new Sudo_8NfaState_5Split(atom_idx2, out_index));
                    return [new _rt.Ok(split_idx), states, budget];
                }
            }
        } else if (_sudo_sc instanceof Sudo_5Quant_4Plus) {
            if (budget <= 0n) {
                return [new _rt.Err(err_size_budget()), states, budget];
            }
            budget = _rt.chk(budget - 1n);
            let split_idx2 = globalThis.BigInt(states.length);
            states.push(new Sudo_8NfaState_5Match());
            let r3;
            [r3, states, budget] = build_atom_fragment(item.atom, split_idx2, states, budget);
            {
                const _sudo_sc = r3;
                if (_sudo_sc instanceof _rt.Err) {
                    const e3 = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(e3)), states, budget];
                } else if (_sudo_sc instanceof _rt.Ok) {
                    const atom_idx3 = _sudo_sc.value;
                    _rt.put(states, split_idx2, new Sudo_8NfaState_5Split(atom_idx3, out_index));
                    return [new _rt.Ok(atom_idx3), states, budget];
                }
            }
        }
    }
}

export function build_nfa(pr, budget) {
    let states = _rt.lst([]);
    states.push(new Sudo_8NfaState_5Match());
    let branch_starts = _rt.lst([]);
    for (const br of pr.branches.slice()) {
        let next_index = 0n;
        let k = _rt.chk(globalThis.BigInt(br.items.length) - 1n);
        while (k >= 0n) {
            let r;
            [r, states, budget] = build_fragment(_rt.at(br.items, k), next_index, states, budget);
            {
                const _sudo_sc = r;
                if (_sudo_sc instanceof _rt.Ok) {
                    const idx = _sudo_sc.value;
                    next_index = idx;
                } else if (_sudo_sc instanceof _rt.Err) {
                    const e = _sudo_sc.error;
                    return [new _rt.Err(_rt.dup(e)), budget];
                }
            }
            k = _rt.chk(k - 1n);
        }
        branch_starts.push(next_index);
    }
    if (globalThis.BigInt(branch_starts.length) === 1n) {
        return [new _rt.Ok(_rt.rec(new CompiledPattern(_rt.dup(states), _rt.at(branch_starts, 0n)))), budget];
    }
    let cur = _rt.at(branch_starts, _rt.chk(globalThis.BigInt(branch_starts.length) - 1n));
    let j = _rt.chk(globalThis.BigInt(branch_starts.length) - 2n);
    while (j >= 0n) {
        if (budget <= 0n) {
            return [new _rt.Err(err_size_budget()), budget];
        }
        budget = _rt.chk(budget - 1n);
        states.push(new Sudo_8NfaState_5Split(_rt.at(branch_starts, j), cur));
        cur = _rt.chk(globalThis.BigInt(states.length) - 1n);
        j = _rt.chk(j - 1n);
    }
    return [new _rt.Ok(_rt.rec(new CompiledPattern(_rt.dup(states), cur))), budget];
}

export function compile_pattern(pattern, is_glob) {
    let budget = max_nfa_states;
    let pr;
    [pr, budget] = parse_pattern(pattern, is_glob, budget);
    {
        const _sudo_sc = pr;
        if (_sudo_sc instanceof _rt.Ok) {
            const parsed = _sudo_sc.value;
            let _sudo_h0;
            [_sudo_h0, budget] = build_nfa(parsed, budget);
            return _sudo_h0;
        } else if (_sudo_sc instanceof _rt.Err) {
            const msg = _sudo_sc.error;
            return new _rt.Err(_rt.dup(msg));
        }
    }
}

export function is_word_scalar(c) {
    if (c === _rt.neg(1n)) {
        return false;
    }
    if (c >= 65n && c <= 90n) {
        return true;
    }
    if (c >= 97n && c <= 122n) {
        return true;
    }
    if (c >= 48n && c <= 57n) {
        return true;
    }
    if (c === 95n) {
        return true;
    }
    return false;
}

export function assert_holds(kind, prev_c, next_c) {
    {
        const _sudo_sc = kind;
        if (_sudo_sc instanceof Sudo_10AssertKind_5Start) {
            return prev_c === _rt.neg(1n);
        } else if (_sudo_sc instanceof Sudo_10AssertKind_3End) {
            return next_c === _rt.neg(1n);
        } else if (_sudo_sc instanceof Sudo_10AssertKind_12WordBoundary) {
            return is_word_scalar(prev_c) !== is_word_scalar(next_c);
        } else if (_sudo_sc instanceof Sudo_10AssertKind_15NotWordBoundary) {
            return is_word_scalar(prev_c) === is_word_scalar(next_c);
        }
    }
}

export function add_state(states, idx, list, visited, prev_c, next_c) {
    if (_rt.at(visited, idx)) {
        return [states, list, visited];
    }
    _rt.put(visited, idx, true);
    {
        const _sudo_sc = _rt.at(states, idx);
        if (_sudo_sc instanceof Sudo_8NfaState_5Split) {
            const o1 = _sudo_sc.out1;
            const o2 = _sudo_sc.out2;
            [states, list, visited] = add_state(states, o1, list, visited, prev_c, next_c);
            [states, list, visited] = add_state(states, o2, list, visited, prev_c, next_c);
        } else if (_sudo_sc instanceof Sudo_8NfaState_7CharLit) {
            const ch = _sudo_sc.ch;
            const out = _sudo_sc.out;
            list.push(idx);
        } else if (_sudo_sc instanceof Sudo_8NfaState_9CharClass) {
            const neg = _sudo_sc.negate;
            const rng = _rt.dup(_sudo_sc.ranges);
            const out = _sudo_sc.out;
            list.push(idx);
        } else if (_sudo_sc instanceof Sudo_8NfaState_6Assert) {
            const kind = _sudo_sc.kind;
            const out = _sudo_sc.out;
            if (assert_holds(kind, prev_c, next_c)) {
                [states, list, visited] = add_state(states, out, list, visited, prev_c, next_c);
            }
        } else if (_sudo_sc instanceof Sudo_8NfaState_5Match) {
            list.push(idx);
        }
    }
    return [states, list, visited];
}

export function is_match_state(s) {
    {
        const _sudo_sc = s;
        if (_sudo_sc instanceof Sudo_8NfaState_5Match) {
            return true;
        } else if (_sudo_sc instanceof Sudo_8NfaState_7CharLit) {
            const a = _sudo_sc.ch;
            const b = _sudo_sc.out;
            return false;
        } else if (_sudo_sc instanceof Sudo_8NfaState_9CharClass) {
            const c = _sudo_sc.negate;
            const d = _rt.dup(_sudo_sc.ranges);
            const e = _sudo_sc.out;
            return false;
        } else if (_sudo_sc instanceof Sudo_8NfaState_5Split) {
            const f = _sudo_sc.out1;
            const g = _sudo_sc.out2;
            return false;
        } else if (_sudo_sc instanceof Sudo_8NfaState_6Assert) {
            const h = _sudo_sc.kind;
            const k = _sudo_sc.out;
            return false;
        }
    }
}

export function run_nfa_single(states, start, input, ignore_case) {
    let n = globalThis.BigInt(input.length);
    let nstates = globalThis.BigInt(states.length);
    let clist = _rt.lst([]);
    let visited = _rt.filled(nstates, false);
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = n;
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            let prev_c = _rt.neg(1n);
            if (i > 0n) {
                prev_c = _rt.at(input, _rt.chk(i - 1n));
            }
            let next_c = _rt.neg(1n);
            if (i < n) {
                next_c = _rt.at(input, i);
            }
            [states, clist, visited] = add_state(states, start, clist, visited, prev_c, next_c);
            for (const s of clist.slice()) {
                if (is_match_state(_rt.at(states, s))) {
                    return [true, states];
                }
            }
            if (i === n) {
                break;
            }
            let c = _rt.at(input, i);
            let nlist = _rt.lst([]);
            let nvisited = _rt.filled(nstates, false);
            let next_prev_c = c;
            let next_next_c = _rt.neg(1n);
            if (_rt.chk(i + 1n) < n) {
                next_next_c = _rt.at(input, _rt.chk(i + 1n));
            }
            for (const s of clist.slice()) {
                {
                    const _sudo_sc = _rt.at(states, s);
                    if (_sudo_sc instanceof Sudo_8NfaState_7CharLit) {
                        const ch = _sudo_sc.ch;
                        const out = _sudo_sc.out;
                        if (ci_eq(ch, c, ignore_case)) {
                            [states, nlist, nvisited] = add_state(states, out, nlist, nvisited, next_prev_c, next_next_c);
                        }
                    } else if (_sudo_sc instanceof Sudo_8NfaState_9CharClass) {
                        const negate = _sudo_sc.negate;
                        const ranges = _rt.dup(_sudo_sc.ranges);
                        const out = _sudo_sc.out;
                        if (class_matches(negate, ranges, c, ignore_case)) {
                            [states, nlist, nvisited] = add_state(states, out, nlist, nvisited, next_prev_c, next_next_c);
                        }
                    } else if (_sudo_sc instanceof Sudo_8NfaState_5Split) {
                        const o1 = _sudo_sc.out1;
                        const o2 = _sudo_sc.out2;
                    } else if (_sudo_sc instanceof Sudo_8NfaState_6Assert) {
                        const akind = _sudo_sc.kind;
                        const aout = _sudo_sc.out;
                    } else if (_sudo_sc instanceof Sudo_8NfaState_5Match) {
                    }
                }
            }
            clist = _rt.dup(nlist);
            visited = _rt.dup(nvisited);
        }
    }
    return [false, states];
}

export function run_nfa(cp, input, ignore_case) {
    let s = _rt.dup(cp.states);
    let _sudo_h0;
    [_sudo_h0, s] = run_nfa_single(s, cp.start, input, ignore_case);
    return _sudo_h0;
}

export function regex_search(pattern, input, ignore_case) {
    let cp = compile_pattern(pattern, false);
    {
        const _sudo_sc = cp;
        if (_sudo_sc instanceof _rt.Ok) {
            const compiled = _sudo_sc.value;
            return new _rt.Ok(run_nfa(compiled, input, ignore_case));
        } else if (_sudo_sc instanceof _rt.Err) {
            const msg = _sudo_sc.error;
            return new _rt.Err(_rt.dup(msg));
        }
    }
}

export function regex_is_valid(pattern) {
    let cp = compile_pattern(pattern, false);
    return _rt.is_ok(cp);
}

export function glob_match(pattern, input, ignore_case) {
    let cp = compile_pattern(pattern, true);
    let compiled = _rt.dup(_rt.unwrap(cp));
    return run_nfa(compiled, input, ignore_case);
}

export function assert_search(pattern, input, ignore_case, expected) {
    let r = regex_search(pattern, input, ignore_case);
    _rt.sudo_assert(_rt.is_ok(r), 1067);
    _rt.sudo_assert_eq(_rt.unwrap(r), expected, 1068);
}

export function assert_err(pattern) {
    let r = regex_search(pattern, _rt.txt(""), false);
    _rt.sudo_assert(_rt.is_err(r), 1072);
}

export function repeat_char(ch, count) {
    let out = _rt.txt("");
    {
        const _sudo_from_i = 1n;
        const _sudo_to_i = count;
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(ch);
        }
    }
    return _rt.dup(out);
}

