// Generated by sudoc from sorting.sudo — do not edit; edit the sudo source.
import * as _rt from "./_sudo_rt.mjs";
import * as sudo_types from "./_sudo_types_impl.mjs";

export function int_ascending(a, b) {
    return a < b;
}

export function int_descending(a, b) {
    return b < a;
}

export function float_ascending(a, b) {
    return a < b;
}

export function int_identity(x) {
    return x;
}

export function packed_key_ascending(a, b) {
    return _rt.div(a, 10n) < _rt.div(b, 10n);
}

export function packed_key_of(x) {
    return _rt.div(x, 10n);
}

export function pair_int_key(p) {
    let k;
    let t;
    [k, t] = p;
    return k;
}

export function pair_int_text_less(a, b) {
    let ak;
    let at;
    [ak, at] = a;
    let bk;
    let bt;
    [bk, bt] = b;
    return ak < bk;
}

export function triple_primary(p) {
    let a;
    let b;
    let c;
    [a, b, c] = p;
    return a;
}

export function triple_secondary(p) {
    let a;
    let b;
    let c;
    [a, b, c] = p;
    return b;
}

export function triple_tertiary(p) {
    let a;
    let b;
    let c;
    [a, b, c] = p;
    return c;
}

export function sudo_7sort_by__Tup4_3i64_List_3i64_List_3i64_3i64(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.at(items, b));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.at(items, a));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.at(items, a));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.at(items, b));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

export function sudo_7sort_by__Element(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.dup(_rt.at(items, b)));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.dup(_rt.at(items, a)));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.dup(_rt.at(items, a)));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.dup(_rt.at(items, b)));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

export function sudo_7sort_by__List_3i64(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.dup(_rt.at(items, b)));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.dup(_rt.at(items, a)));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.dup(_rt.at(items, a)));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.dup(_rt.at(items, b)));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

export function sudo_11sort_by_key__Tup3_3i64_3i64_3i64_3i64(items, key, less) {
    let keys = _rt.lst([]);
    for (const x of items.slice()) {
        keys.push(key(x));
    }
    let perm = sudo_18sort_index_of_keys__3i64(keys, less);
    items = sudo_17apply_permutation__Tup3_3i64_3i64_3i64(items, perm);
    return items;
}

export function sudo_17apply_permutation__Tup3_3i64_3i64_3i64(items, perm) {
    _rt.sudo_assert_eq(globalThis.BigInt(perm.length), globalThis.BigInt(items.length), 168);
    let n = globalThis.BigInt(items.length);
    let out = _rt.lst([]);
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(n - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(_rt.at(items, _rt.at(perm, i)));
        }
    }
    items = _rt.dup(out);
    return items;
}

export function sudo_13binary_search__3i64(items, target, less) {
    let lo = 0n;
    let hi = globalThis.BigInt(items.length);
    while (lo < hi) {
        let mid = _rt.div(_rt.chk(lo + hi), 2n);
        if (less(_rt.at(items, mid), target)) {
            lo = _rt.chk(mid + 1n);
        } else {
            hi = mid;
        }
    }
    if (lo < globalThis.BigInt(items.length) && !less(target, _rt.at(items, lo))) {
        return new _rt.Some(lo);
    }
    return _rt.NONE;
}

export function sudo_11lower_bound__3i64(items, target, less) {
    let lo = 0n;
    let hi = globalThis.BigInt(items.length);
    while (lo < hi) {
        let mid = _rt.div(_rt.chk(lo + hi), 2n);
        if (less(_rt.at(items, mid), target)) {
            lo = _rt.chk(mid + 1n);
        } else {
            hi = mid;
        }
    }
    return lo;
}

export function sudo_18sort_index_of_keys__3i64(keys, less) {
    let n = globalThis.BigInt(keys.length);
    let idx = _rt.lst([]);
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(n - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            idx.push(i);
        }
    }
    if (n < 2n) {
        return _rt.dup(idx);
    }
    let buf = _rt.dup(idx);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(keys, _rt.at(idx, b)), _rt.at(keys, _rt.at(idx, a)))) {
                    _rt.put(buf, k, _rt.at(idx, b));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.at(idx, a));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.at(idx, a));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.at(idx, b));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [idx, buf] = [buf, idx];
        width = _rt.chk(width * 2n);
    }
    return _rt.dup(idx);
}

export function sudo_17apply_permutation__3i64(items, perm) {
    _rt.sudo_assert_eq(globalThis.BigInt(perm.length), globalThis.BigInt(items.length), 168);
    let n = globalThis.BigInt(items.length);
    let out = _rt.lst([]);
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(n - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(_rt.at(items, _rt.at(perm, i)));
        }
    }
    items = _rt.dup(out);
    return items;
}

export function sudo_11sort_by_key__Tup2_3i64_List_3i64_3i64(items, key, less) {
    let keys = _rt.lst([]);
    for (const x of items.slice()) {
        keys.push(key(x));
    }
    let perm = sudo_18sort_index_of_keys__3i64(keys, less);
    items = sudo_17apply_permutation__Tup2_3i64_List_3i64(items, perm);
    return items;
}

export function sudo_17apply_permutation__Tup2_3i64_List_3i64(items, perm) {
    _rt.sudo_assert_eq(globalThis.BigInt(perm.length), globalThis.BigInt(items.length), 168);
    let n = globalThis.BigInt(items.length);
    let out = _rt.lst([]);
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(n - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(_rt.dup(_rt.at(items, _rt.at(perm, i))));
        }
    }
    items = _rt.dup(out);
    return items;
}

export function sudo_7sort_by__Tup2_3i64_List_3i64(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.at(items, b));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.at(items, a));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.at(items, a));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.at(items, b));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

export function sudo_11sort_by_key__3i64_3i64(items, key, less) {
    let keys = _rt.lst([]);
    for (const x of items.slice()) {
        keys.push(key(x));
    }
    let perm = sudo_18sort_index_of_keys__3i64(keys, less);
    items = sudo_17apply_permutation__3i64(items, perm);
    return items;
}

export function sudo_8reversed__3i64(items) {
    let out = _rt.lst([]);
    {
        const _sudo_from_i = _rt.chk(globalThis.BigInt(items.length) - 1n);
        const _sudo_to_i = 0n;
        for (let i = _sudo_from_i; i >= _sudo_to_i; i -= 1n) {
            out.push(_rt.at(items, i));
        }
    }
    return _rt.dup(out);
}

export function sudo_10maximum_by__3i64(items, less) {
    if (globalThis.BigInt(items.length) === 0n) {
        return _rt.NONE;
    }
    let best = _rt.at(items, 0n);
    for (const x of items.slice()) {
        if (less(best, x)) {
            best = x;
        }
    }
    return new _rt.Some(best);
}

export function sudo_10minimum_by__3i64(items, less) {
    if (globalThis.BigInt(items.length) === 0n) {
        return _rt.NONE;
    }
    let best = _rt.at(items, 0n);
    for (const x of items.slice()) {
        if (less(x, best)) {
            best = x;
        }
    }
    return new _rt.Some(best);
}

export function sudo_7sort_by__3f64(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.at(items, b));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.at(items, a));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.at(items, a));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.at(items, b));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

export function sudo_12is_sorted_by__3i64(items, less) {
    {
        const _sudo_from_i = 1n;
        const _sudo_to_i = _rt.chk(globalThis.BigInt(items.length) - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            if (less(_rt.at(items, i), _rt.at(items, _rt.chk(i - 1n)))) {
                return false;
            }
        }
    }
    return true;
}

export function sudo_7sort_by__3i64(items, less) {
    let n = globalThis.BigInt(items.length);
    if (n < 2n) {
        return items;
    }
    let buf = _rt.dup(items);
    let width = 1n;
    while (width < n) {
        let i = 0n;
        while (i < n) {
            let mid = ((_rt.chk(i + width)) < (n) ? (_rt.chk(i + width)) : (n));
            let right = ((_rt.chk(i + _rt.chk(2n * width))) < (n) ? (_rt.chk(i + _rt.chk(2n * width))) : (n));
            let a = i;
            let b = mid;
            let k = i;
            while (a < mid && b < right) {
                if (less(_rt.at(items, b), _rt.at(items, a))) {
                    _rt.put(buf, k, _rt.at(items, b));
                    b = _rt.chk(b + 1n);
                } else {
                    _rt.put(buf, k, _rt.at(items, a));
                    a = _rt.chk(a + 1n);
                }
                k = _rt.chk(k + 1n);
            }
            while (a < mid) {
                _rt.put(buf, k, _rt.at(items, a));
                a = _rt.chk(a + 1n);
                k = _rt.chk(k + 1n);
            }
            while (b < right) {
                _rt.put(buf, k, _rt.at(items, b));
                b = _rt.chk(b + 1n);
                k = _rt.chk(k + 1n);
            }
            i = _rt.chk(i + _rt.chk(2n * width));
        }
        [items, buf] = [buf, items];
        width = _rt.chk(width * 2n);
    }
    return items;
}

