// Generated by sudoc from strings.sudo — do not edit; edit the sudo source.
import * as _rt from "./_sudo_rt.mjs";

export function lex_compare(a, b) {
    let n = ((globalThis.BigInt(a.length)) < (globalThis.BigInt(b.length)) ? (globalThis.BigInt(a.length)) : (globalThis.BigInt(b.length)));
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(n - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            if (_rt.at(a, i) < _rt.at(b, i)) {
                return _rt.neg(1n);
            }
            if (_rt.at(b, i) < _rt.at(a, i)) {
                return 1n;
            }
        }
    }
    if (globalThis.BigInt(a.length) < globalThis.BigInt(b.length)) {
        return _rt.neg(1n);
    }
    if (globalThis.BigInt(b.length) < globalThis.BigInt(a.length)) {
        return 1n;
    }
    return 0n;
}

export function lex_less(a, b) {
    return lex_compare(a, b) < 0n;
}

export function starts_with(s, prefix) {
    if (globalThis.BigInt(prefix.length) > globalThis.BigInt(s.length)) {
        return false;
    }
    return match_at(s, prefix, 0n);
}

export function ends_with(s, suffix) {
    if (globalThis.BigInt(suffix.length) > globalThis.BigInt(s.length)) {
        return false;
    }
    return match_at(s, suffix, _rt.chk(globalThis.BigInt(s.length) - globalThis.BigInt(suffix.length)));
}

export function match_at(hay, needle, start) {
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(globalThis.BigInt(needle.length) - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            if (_rt.at(hay, _rt.chk(start + i)) !== _rt.at(needle, i)) {
                return false;
            }
        }
    }
    return true;
}

export function index_of(hay, needle) {
    if (globalThis.BigInt(needle.length) === 0n) {
        return new _rt.Some(0n);
    }
    if (globalThis.BigInt(needle.length) > globalThis.BigInt(hay.length)) {
        return _rt.NONE;
    }
    {
        const _sudo_from_start = 0n;
        const _sudo_to_start = _rt.chk(globalThis.BigInt(hay.length) - globalThis.BigInt(needle.length));
        for (let start = _sudo_from_start; start <= _sudo_to_start; start += 1n) {
            let matched = true;
            {
                const _sudo_from_j = 0n;
                const _sudo_to_j = _rt.chk(globalThis.BigInt(needle.length) - 1n);
                for (let j = _sudo_from_j; j <= _sudo_to_j; j += 1n) {
                    if (_rt.at(hay, _rt.chk(start + j)) !== _rt.at(needle, j)) {
                        matched = false;
                        break;
                    }
                }
            }
            if (matched) {
                return new _rt.Some(start);
            }
        }
    }
    return _rt.NONE;
}

export function contains(hay, needle) {
    return _rt.is_some(index_of(hay, needle));
}

export function split(s, sep) {
    let parts = _rt.lst([]);
    let current = _rt.txt("");
    {
        const _sudo_from_i = 0n;
        const _sudo_to_i = _rt.chk(globalThis.BigInt(s.length) - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            if (_rt.at(s, i) === sep) {
                parts.push(_rt.dup(current));
                current = _rt.txt("");
            } else {
                current.push(_rt.at(s, i));
            }
        }
    }
    parts.push(_rt.dup(current));
    return _rt.dup(parts);
}

export function join(parts, sep) {
    let out = _rt.txt("");
    let first = true;
    for (const p of parts.slice()) {
        if (!first) {
            out.push(sep);
        }
        first = false;
        for (const c of p.slice()) {
            out.push(c);
        }
    }
    return _rt.dup(out);
}

export function to_upper(s) {
    let out = _rt.txt("");
    for (const c of s.slice()) {
        if (c >= 97n && c <= 122n) {
            out.push(_rt.chk(c - 32n));
        } else {
            out.push(c);
        }
    }
    return _rt.dup(out);
}

export function to_lower(s) {
    let out = _rt.txt("");
    for (const c of s.slice()) {
        if (c >= 65n && c <= 90n) {
            out.push(_rt.chk(c + 32n));
        } else {
            out.push(c);
        }
    }
    return _rt.dup(out);
}

export function substring(s, start, end) {
    if (start < 0n || end > globalThis.BigInt(s.length) || start > end) {
        let discard = _rt.at(s, globalThis.BigInt(s.length));
        return _rt.txt("");
    }
    let out = _rt.txt("");
    {
        const _sudo_from_i = start;
        const _sudo_to_i = _rt.chk(end - 1n);
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(_rt.at(s, i));
        }
    }
    return _rt.dup(out);
}

export function last_index_of(hay, needle) {
    if (globalThis.BigInt(needle.length) === 0n) {
        return new _rt.Some(globalThis.BigInt(hay.length));
    }
    if (globalThis.BigInt(needle.length) > globalThis.BigInt(hay.length)) {
        return _rt.NONE;
    }
    {
        const _sudo_from_start = _rt.chk(globalThis.BigInt(hay.length) - globalThis.BigInt(needle.length));
        const _sudo_to_start = 0n;
        for (let start = _sudo_from_start; start >= _sudo_to_start; start -= 1n) {
            let matched = true;
            {
                const _sudo_from_j = 0n;
                const _sudo_to_j = _rt.chk(globalThis.BigInt(needle.length) - 1n);
                for (let j = _sudo_from_j; j <= _sudo_to_j; j += 1n) {
                    if (_rt.at(hay, _rt.chk(start + j)) !== _rt.at(needle, j)) {
                        matched = false;
                        break;
                    }
                }
            }
            if (matched) {
                return new _rt.Some(start);
            }
        }
    }
    return _rt.NONE;
}

export function replace(s, needle, repl) {
    if (globalThis.BigInt(needle.length) === 0n) {
        return _rt.dup(s);
    }
    let out = _rt.txt("");
    let i = 0n;
    while (i < globalThis.BigInt(s.length)) {
        let matched = false;
        if (_rt.chk(i + globalThis.BigInt(needle.length)) <= globalThis.BigInt(s.length)) {
            matched = true;
            {
                const _sudo_from_j = 0n;
                const _sudo_to_j = _rt.chk(globalThis.BigInt(needle.length) - 1n);
                for (let j = _sudo_from_j; j <= _sudo_to_j; j += 1n) {
                    if (_rt.at(s, _rt.chk(i + j)) !== _rt.at(needle, j)) {
                        matched = false;
                        break;
                    }
                }
            }
        }
        if (matched) {
            for (const c of repl.slice()) {
                out.push(c);
            }
            i = _rt.chk(i + globalThis.BigInt(needle.length));
        } else {
            out.push(_rt.at(s, i));
            i = _rt.chk(i + 1n);
        }
    }
    return _rt.dup(out);
}

export function repeat(s, n) {
    if (n < 0n) {
        let discard = _rt.filled(n, 0n);
        return _rt.txt("");
    }
    if (n === 0n || globalThis.BigInt(s.length) === 0n) {
        return _rt.txt("");
    }
    let total = _rt.chk(globalThis.BigInt(s.length) * n);
    let out = _rt.filled(total, 0n);
    let k = 0n;
    {
        const _sudo_from_i = 1n;
        const _sudo_to_i = n;
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            for (const c of s.slice()) {
                _rt.put(out, k, c);
                k = _rt.chk(k + 1n);
            }
        }
    }
    return _rt.dup(out);
}

export function pad_left(s, width, fill) {
    if (globalThis.BigInt(s.length) >= width) {
        return _rt.dup(s);
    }
    let out = _rt.txt("");
    {
        const _sudo_from_i = 1n;
        const _sudo_to_i = _rt.chk(width - globalThis.BigInt(s.length));
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(fill);
        }
    }
    for (const c of s.slice()) {
        out.push(c);
    }
    return _rt.dup(out);
}

export function pad_right(s, width, fill) {
    if (globalThis.BigInt(s.length) >= width) {
        return _rt.dup(s);
    }
    let out = _rt.txt("");
    for (const c of s.slice()) {
        out.push(c);
    }
    {
        const _sudo_from_i = 1n;
        const _sudo_to_i = _rt.chk(width - globalThis.BigInt(s.length));
        for (let i = _sudo_from_i; i <= _sudo_to_i; i += 1n) {
            out.push(fill);
        }
    }
    return _rt.dup(out);
}

export function is_space(c) {
    if (c === 32n) {
        return true;
    }
    if (c >= 9n && c <= 13n) {
        return true;
    }
    return false;
}

export function trim_left(s) {
    let i = 0n;
    while (i < globalThis.BigInt(s.length) && is_space(_rt.at(s, i))) {
        i = _rt.chk(i + 1n);
    }
    return substring(s, i, globalThis.BigInt(s.length));
}

export function trim_right(s) {
    let end = globalThis.BigInt(s.length);
    while (end > 0n && is_space(_rt.at(s, _rt.chk(end - 1n)))) {
        end = _rt.chk(end - 1n);
    }
    return substring(s, 0n, end);
}

export function trim(s) {
    return trim_right(trim_left(s));
}

export function split_str(s, sep) {
    if (globalThis.BigInt(sep.length) === 0n) {
        return _rt.lst([_rt.dup(s)]);
    }
    let parts = _rt.lst([]);
    let current = _rt.txt("");
    let i = 0n;
    while (i < globalThis.BigInt(s.length)) {
        let matched = false;
        if (_rt.chk(i + globalThis.BigInt(sep.length)) <= globalThis.BigInt(s.length)) {
            matched = true;
            {
                const _sudo_from_j = 0n;
                const _sudo_to_j = _rt.chk(globalThis.BigInt(sep.length) - 1n);
                for (let j = _sudo_from_j; j <= _sudo_to_j; j += 1n) {
                    if (_rt.at(s, _rt.chk(i + j)) !== _rt.at(sep, j)) {
                        matched = false;
                        break;
                    }
                }
            }
        }
        if (matched) {
            parts.push(_rt.dup(current));
            current = _rt.txt("");
            i = _rt.chk(i + globalThis.BigInt(sep.length));
        } else {
            current.push(_rt.at(s, i));
            i = _rt.chk(i + 1n);
        }
    }
    parts.push(_rt.dup(current));
    return _rt.dup(parts);
}

export function strip_prefix(s, prefix) {
    if (starts_with(s, prefix)) {
        return new _rt.Some(substring(s, globalThis.BigInt(prefix.length), globalThis.BigInt(s.length)));
    }
    return _rt.NONE;
}

export function strip_suffix(s, suffix) {
    if (ends_with(s, suffix)) {
        return new _rt.Some(substring(s, 0n, _rt.chk(globalThis.BigInt(s.length) - globalThis.BigInt(suffix.length))));
    }
    return _rt.NONE;
}

