// Generated by sudoc from sudo_types.sudo — do not edit; edit the sudo source.
import * as _rt from "./_sudo_rt.mjs";

export class Element {
    static _sudoKind = ["r", "Element"];
    static _sudoFields = ["name", "emoji", "first"];
    constructor(name, emoji, first) {
        this.name = name;
        this.emoji = emoji;
        this.first = first;
    }
}

