// Host-facing API for craft.sudo — generated by sudoc. Traps throw
// _rt.SudoTrap; Err results throw _rt.SudoError; invalid inputs throw
// TypeError/RangeError (see _sudo_rt.mjs).
import * as _impl from "./_craft_impl.mjs";
import * as _rt from "./_sudo_rt.mjs";

export function is_base_element(name) {
    name = _rt.host_text(name);
    const _r = _impl.is_base_element(name);
    return _r;
}

export function title_case(s) {
    s = _rt.host_text(s);
    const _r = _impl.title_case(s);
    return _rt.text_str(_r);
}

export function sanitize_element_name(name) {
    name = _rt.host_text(name);
    const _r = _impl.sanitize_element_name(name);
    return _rt.text_str(_r);
}

export function pair_key(a, b) {
    a = _rt.host_text(a);
    b = _rt.host_text(b);
    const _r = _impl.pair_key(a, b);
    return [_rt.text_str(_r[0]), _rt.text_str(_r[1])];
}

export function record_recipe(recipes, result_name, a_name, b_name) {
    const _in_recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    result_name = _rt.host_text(result_name);
    a_name = _rt.host_text(a_name);
    b_name = _rt.host_text(b_name);
    const _new_recipes = _impl.record_recipe(_in_recipes, result_name, a_name, b_name);
    _rt.writeback_map(recipes, _new_recipes, (_k) => _rt.text_str(_k), (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]));
}

export function record_recipes_batch(recipes, entries) {
    const _in_recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    entries = _rt.host_list(entries, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)]));
    const _new_recipes = _impl.record_recipes_batch(_in_recipes, entries);
    _rt.writeback_map(recipes, _new_recipes, (_k) => _rt.text_str(_k), (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]));
}

export function ingredient_usage_counts(recipes) {
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.ingredient_usage_counts(recipes);
    return _rt.out_map(_r, (_k) => _rt.text_str(_k), (_v) => _rt.int_out(_v));
}

export function is_unfilled(name, recipes) {
    name = _rt.host_text(name);
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.is_unfilled(name, recipes);
    return _r;
}

export function parse_query_filter(query) {
    query = _rt.host_text(query);
    const _r = _impl.parse_query_filter(query);
    return [_rt.text_str(_r[0]), _r[1], _r[2]];
}

export function is_delimited_regex(pattern) {
    pattern = _rt.host_text(pattern);
    const _r = _impl.is_delimited_regex(pattern);
    return _r;
}

export function element_matches_pattern(name, pattern) {
    name = _rt.host_text(name);
    pattern = _rt.host_text(pattern);
    const _r = _impl.element_matches_pattern(name, pattern);
    return [_r[0], _rt.out_option(_r[1], (_v) => _rt.text_str(_v))];
}

export function slash_args(line, command) {
    line = _rt.host_text(line);
    command = _rt.host_text(command);
    const _r = _impl.slash_args(line, command);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function is_local_command(line) {
    line = _rt.host_text(line);
    const _r = _impl.is_local_command(line);
    return _r;
}

export function is_ib_command(line) {
    line = _rt.host_text(line);
    const _r = _impl.is_ib_command(line);
    return _r;
}

export function known_slash_commands() {
    const _r = _impl.known_slash_commands();
    return _r.map((_v) => _rt.text_str(_v));
}

export function is_known_slash_command(line) {
    line = _rt.host_text(line);
    const _r = _impl.is_known_slash_command(line);
    return _r;
}

export function runs_local(line) {
    line = _rt.host_text(line);
    const _r = _impl.runs_local(line);
    return _r;
}

export function command_queue_lane(line) {
    line = _rt.host_text(line);
    const _r = _impl.command_queue_lane(line);
    return _rt.text_str(_r);
}

export function queue_accept(line, current, lane_queue, total_pending, max_depth) {
    line = _rt.host_text(line);
    current = _rt.host_text(current);
    lane_queue = _rt.host_list(lane_queue, (_v) => _rt.host_text(_v));
    total_pending = _rt.host_int(total_pending);
    max_depth = _rt.host_int(max_depth);
    const _r = _impl.queue_accept(line, current, lane_queue, total_pending, max_depth);
    return _rt.text_str(_r);
}

export function queue_lane_busy(current, pending_len, confirm_active) {
    current = _rt.host_text(current);
    pending_len = _rt.host_int(pending_len);
    confirm_active = _rt.host_bool(confirm_active);
    const _r = _impl.queue_lane_busy(current, pending_len, confirm_active);
    return _r;
}

export function lane_should_reset_cancel(lane, peer_busy, confirm_active) {
    lane = _rt.host_text(lane);
    peer_busy = _rt.host_bool(peer_busy);
    confirm_active = _rt.host_bool(confirm_active);
    const _r = _impl.lane_should_reset_cancel(lane, peer_busy, confirm_active);
    return _r;
}

export function lane_should_soft_reset_cancel(lane, peer_busy) {
    lane = _rt.host_text(lane);
    peer_busy = _rt.host_bool(peer_busy);
    const _r = _impl.lane_should_soft_reset_cancel(lane, peer_busy);
    return _r;
}

export function may_bulk_confirm(line) {
    line = _rt.host_text(line);
    const _r = _impl.may_bulk_confirm(line);
    return _r;
}

export function should_bulk_warn(n, threshold) {
    n = _rt.host_int(n);
    threshold = _rt.host_int(threshold);
    const _r = _impl.should_bulk_warn(n, threshold);
    return _r;
}

export function parse_target_arg(arg) {
    arg = _rt.host_text(arg);
    const _r = _impl.parse_target_arg(arg);
    return [_rt.text_str(_r[0]), _rt.text_str(_r[1])];
}

export function is_target_hit(target, result_name) {
    target = _rt.host_text(target);
    result_name = _rt.host_text(result_name);
    const _r = _impl.is_target_hit(target, result_name);
    return _r;
}

export function target_outcome(prev, action, name) {
    prev = _rt.host_text(prev);
    action = _rt.host_text(action);
    name = _rt.host_text(name);
    const _r = _impl.target_outcome(prev, action, name);
    return [_rt.text_str(_r[0]), _rt.text_str(_r[1]), _rt.text_str(_r[2])];
}

export function apply_target_state(current, action, name) {
    current = _rt.host_text(current);
    action = _rt.host_text(action);
    name = _rt.host_text(name);
    const _r = _impl.apply_target_state(current, action, name);
    return _rt.text_str(_r);
}

export function auto_approve_outcome(prev, arg) {
    prev = _rt.host_bool(prev);
    arg = _rt.host_text(arg);
    const _r = _impl.auto_approve_outcome(prev, arg);
    return [_rt.text_str(_r[0]), _r[1]];
}

export function relay_toggle_outcome(prev, arg) {
    prev = _rt.host_bool(prev);
    arg = _rt.host_text(arg);
    const _r = _impl.relay_toggle_outcome(prev, arg);
    return [_rt.text_str(_r[0]), _r[1]];
}

export function relay_reseed_entries(elements, recipes) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.relay_reseed_entries(elements, recipes);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _rt.text_str(_v[2]), _rt.text_str(_v[3])]);
}

export function bulk_confirm_required(n, threshold, auto_approve) {
    n = _rt.host_int(n);
    threshold = _rt.host_int(threshold);
    auto_approve = _rt.host_bool(auto_approve);
    const _r = _impl.bulk_confirm_required(n, threshold, auto_approve);
    return _r;
}

export function confirm_answer_key(answer) {
    answer = _rt.host_text(answer);
    const _r = _impl.confirm_answer_key(answer);
    return _rt.text_str(_r);
}

export function confirm_should_continue(answer) {
    answer = _rt.host_text(answer);
    const _r = _impl.confirm_should_continue(answer);
    return _r;
}

export function is_confirm_answer(answer) {
    answer = _rt.host_text(answer);
    const _r = _impl.is_confirm_answer(answer);
    return _r;
}

export function confirm_input_route(answer, waiting, bulk_pending) {
    answer = _rt.host_text(answer);
    waiting = _rt.host_bool(waiting);
    bulk_pending = _rt.host_bool(bulk_pending);
    const _r = _impl.confirm_input_route(answer, waiting, bulk_pending);
    return _rt.text_str(_r);
}

export function fetch_timeout_ms() {
    const _r = _impl.fetch_timeout_ms();
    return _rt.int_out(_r);
}

export function pair_retry_max_attempts() {
    const _r = _impl.pair_retry_max_attempts();
    return _rt.int_out(_r);
}

export function pair_retry_backoff_ms(attempt) {
    attempt = _rt.host_int(attempt);
    const _r = _impl.pair_retry_backoff_ms(attempt);
    return _rt.int_out(_r);
}

export function pair_should_retry(attempt) {
    attempt = _rt.host_int(attempt);
    const _r = _impl.pair_should_retry(attempt);
    return _r;
}

export function ib_retry_max_attempts() {
    const _r = _impl.ib_retry_max_attempts();
    return _rt.int_out(_r);
}

export function ib_retry_backoff_ms(attempt) {
    attempt = _rt.host_int(attempt);
    const _r = _impl.ib_retry_backoff_ms(attempt);
    return _rt.int_out(_r);
}

export function ib_should_retry(status, attempt) {
    status = _rt.host_int(status);
    attempt = _rt.host_int(attempt);
    const _r = _impl.ib_should_retry(status, attempt);
    return _r;
}

export function script_tokenize(source) {
    source = _rt.host_text(source);
    const _r = _impl.script_tokenize(source);
    return [_r[0], _r[1].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _rt.int_out(_v[2])]), _rt.text_str(_r[2]), _rt.int_out(_r[3])];
}

export function script_tokens_repr(tokens) {
    tokens = _rt.host_list(tokens, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_int(_v)]));
    const _r = _impl.script_tokens_repr(tokens);
    return _rt.text_str(_r);
}

export function script_parse(source) {
    source = _rt.host_text(source);
    const _r = _impl.script_parse(source);
    return [_r[0], _r[1].map((_v) => [_rt.text_str(_v[0]), _rt.int_out(_v[1]), _rt.int_out(_v[2]), _rt.int_out(_v[3]), _rt.text_str(_v[4])]), _r[2].map((_v) => _v.map((_v) => _rt.int_out(_v))), _r[3].map((_v) => _v), _rt.text_str(_r[4]), _rt.int_out(_r[5])];
}

export function script_ast_repr(nodes, kids, id) {
    nodes = _rt.host_list(nodes, (_v) => _rt.host_tuple(_v, 5, [(_v) => _rt.host_text(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_text(_v)]));
    kids = _rt.host_list(kids, (_v) => _rt.host_list(_v, (_v) => _rt.host_int(_v)));
    id = _rt.host_int(id);
    const _r = _impl.script_ast_repr(nodes, kids, id);
    return _rt.text_str(_r);
}

export function script_set_op_boundary(op, a, b, recipes) {
    op = _rt.host_text(op);
    a = _rt.host_list(a, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    b = _rt.host_list(b, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.script_set_op_boundary(op, a, b, recipes);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function script_eval_expr_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed) {
    nodes = _rt.host_list(nodes, (_v) => _rt.host_tuple(_v, 5, [(_v) => _rt.host_text(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_text(_v)]));
    kids = _rt.host_list(kids, (_v) => _rt.host_list(_v, (_v) => _rt.host_int(_v)));
    id = _rt.host_int(id);
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    env_names = _rt.host_list(env_names, (_v) => _rt.host_text(_v));
    env_values = _rt.host_list(env_values, (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)])));
    newreg = _rt.host_list(newreg, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    seed = _rt.host_int(seed);
    const _r = _impl.script_eval_expr_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed);
    return [_r[0], _r[1].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]), _rt.text_str(_r[2])];
}

export function script_eval_cond_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed) {
    nodes = _rt.host_list(nodes, (_v) => _rt.host_tuple(_v, 5, [(_v) => _rt.host_text(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_text(_v)]));
    kids = _rt.host_list(kids, (_v) => _rt.host_list(_v, (_v) => _rt.host_int(_v)));
    id = _rt.host_int(id);
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    env_names = _rt.host_list(env_names, (_v) => _rt.host_text(_v));
    env_values = _rt.host_list(env_values, (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)])));
    newreg = _rt.host_list(newreg, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    seed = _rt.host_int(seed);
    const _r = _impl.script_eval_cond_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed);
    return [_r[0], _r[1], _rt.text_str(_r[2])];
}

export function script_eval_num_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed) {
    nodes = _rt.host_list(nodes, (_v) => _rt.host_tuple(_v, 5, [(_v) => _rt.host_text(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_text(_v)]));
    kids = _rt.host_list(kids, (_v) => _rt.host_list(_v, (_v) => _rt.host_int(_v)));
    id = _rt.host_int(id);
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    env_names = _rt.host_list(env_names, (_v) => _rt.host_text(_v));
    env_values = _rt.host_list(env_values, (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)])));
    newreg = _rt.host_list(newreg, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    seed = _rt.host_int(seed);
    const _r = _impl.script_eval_num_boundary(nodes, kids, id, elements, recipes, env_names, env_values, newreg, seed);
    return [_r[0], _rt.int_out(_r[1]), _rt.text_str(_r[2])];
}

export function script_take_tuples(items, n) {
    items = _rt.host_list(items, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    n = _rt.host_int(n);
    const _r = _impl.script_take_tuples(items, n);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function script_sample_tuples(items, n, seed) {
    items = _rt.host_list(items, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    n = _rt.host_int(n);
    seed = _rt.host_int(seed);
    const _r = _impl.script_sample_tuples(items, n, seed);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function script_union_tuples(a, b) {
    a = _rt.host_list(a, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    b = _rt.host_list(b, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const _r = _impl.script_union_tuples(a, b);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function lucky_pairs_boundary(elements, recipes, tried, n, seed) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    tried = _rt.host_list(tried, (_v) => _rt.host_text(_v));
    n = _rt.host_int(n);
    seed = _rt.host_int(seed);
    const _r = _impl.lucky_pairs_boundary(elements, recipes, tried, n, seed);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function rate_status_note(remaining) {
    remaining = _rt.host_int(remaining);
    const _r = _impl.rate_status_note(remaining);
    return _rt.text_str(_r);
}

export function rate_slots_left(used, max_requests) {
    used = _rt.host_int(used);
    max_requests = _rt.host_int(max_requests);
    const _r = _impl.rate_slots_left(used, max_requests);
    return _rt.int_out(_r);
}

export function rate_next_slot_frac_milli(now_ms, oldest_ms, last_freed_ms, window_ms, has_timestamps, has_last_freed) {
    now_ms = _rt.host_int(now_ms);
    oldest_ms = _rt.host_int(oldest_ms);
    last_freed_ms = _rt.host_int(last_freed_ms);
    window_ms = _rt.host_int(window_ms);
    has_timestamps = _rt.host_bool(has_timestamps);
    has_last_freed = _rt.host_bool(has_last_freed);
    const _r = _impl.rate_next_slot_frac_milli(now_ms, oldest_ms, last_freed_ms, window_ms, has_timestamps, has_last_freed);
    return _rt.int_out(_r);
}

export function rate_bar_fills(remaining, max_requests, frac_milli, left_width, right_width) {
    remaining = _rt.host_int(remaining);
    max_requests = _rt.host_int(max_requests);
    frac_milli = _rt.host_int(frac_milli);
    left_width = _rt.host_int(left_width);
    right_width = _rt.host_int(right_width);
    const _r = _impl.rate_bar_fills(remaining, max_requests, frac_milli, left_width, right_width);
    return [_rt.int_out(_r[0]), _rt.int_out(_r[1])];
}

export function rate_bar_fills_split(remaining, fleet_used, max_requests, frac_milli, left_width, right_width) {
    remaining = _rt.host_int(remaining);
    fleet_used = _rt.host_int(fleet_used);
    max_requests = _rt.host_int(max_requests);
    frac_milli = _rt.host_int(frac_milli);
    left_width = _rt.host_int(left_width);
    right_width = _rt.host_int(right_width);
    const _r = _impl.rate_bar_fills_split(remaining, fleet_used, max_requests, frac_milli, left_width, right_width);
    return [_rt.int_out(_r[0]), _rt.int_out(_r[1]), _rt.int_out(_r[2])];
}

export function rate_bar_split_segments(remaining, fleet_used, max_requests, frac_milli, left_width, right_width) {
    remaining = _rt.host_int(remaining);
    fleet_used = _rt.host_int(fleet_used);
    max_requests = _rt.host_int(max_requests);
    frac_milli = _rt.host_int(frac_milli);
    left_width = _rt.host_int(left_width);
    right_width = _rt.host_int(right_width);
    const _r = _impl.rate_bar_split_segments(remaining, fleet_used, max_requests, frac_milli, left_width, right_width);
    return [_rt.text_str(_r[0]), _rt.text_str(_r[1]), _rt.text_str(_r[2]), _rt.text_str(_r[3])];
}

export function effective_rate_limit(max_requests, spending_peers) {
    max_requests = _rt.host_int(max_requests);
    spending_peers = _rt.host_int(spending_peers);
    const _r = _impl.effective_rate_limit(max_requests, spending_peers);
    return _rt.int_out(_r);
}

export function cooldown_duration_ms(strikes) {
    strikes = _rt.host_int(strikes);
    const _r = _impl.cooldown_duration_ms(strikes);
    return _rt.int_out(_r);
}

export function bounty_poll_interval_ms() {
    const _r = _impl.bounty_poll_interval_ms();
    return _rt.int_out(_r);
}

export function bounty_sync_interval_ms() {
    const _r = _impl.bounty_sync_interval_ms();
    return _rt.int_out(_r);
}

export function bounty_lease_ttl_ms() {
    const _r = _impl.bounty_lease_ttl_ms();
    return _rt.int_out(_r);
}

export function bounty_legacy_ttl_ms() {
    const _r = _impl.bounty_legacy_ttl_ms();
    return _rt.int_out(_r);
}

export function bounty_session_quota() {
    const _r = _impl.bounty_session_quota();
    return _rt.int_out(_r);
}

export function bounty_sync_plan(miss_count, slots_left, effective_max) {
    miss_count = _rt.host_int(miss_count);
    slots_left = _rt.host_int(slots_left);
    effective_max = _rt.host_int(effective_max);
    const _r = _impl.bounty_sync_plan(miss_count, slots_left, effective_max);
    return [_rt.int_out(_r[0]), _rt.int_out(_r[1])];
}

export function bounty_claim_limit(slots_left) {
    slots_left = _rt.host_int(slots_left);
    const _r = _impl.bounty_claim_limit(slots_left);
    return _rt.int_out(_r);
}

export function bounty_poll_hint_ms(open_bounties, eligible) {
    open_bounties = _rt.host_int(open_bounties);
    eligible = _rt.host_bool(eligible);
    const _r = _impl.bounty_poll_hint_ms(open_bounties, eligible);
    return _rt.int_out(_r);
}

export function relay_retry_interval_ms() {
    const _r = _impl.relay_retry_interval_ms();
    return _rt.int_out(_r);
}

export function hive_wait_tick_ms() {
    const _r = _impl.hive_wait_tick_ms();
    return _rt.int_out(_r);
}

export function hive_resweep_interval_ms() {
    const _r = _impl.hive_resweep_interval_ms();
    return _rt.int_out(_r);
}

export function rate_bar_segment(filled, width) {
    filled = _rt.host_int(filled);
    width = _rt.host_int(width);
    const _r = _impl.rate_bar_segment(filled, width);
    return _rt.text_str(_r);
}

export function rate_ellipsize_end(s, max_chars) {
    s = _rt.host_text(s);
    max_chars = _rt.host_int(max_chars);
    const _r = _impl.rate_ellipsize_end(s, max_chars);
    return _rt.text_str(_r);
}

export function rate_format_pair_for_width(a, b, avail) {
    a = _rt.host_text(a);
    b = _rt.host_text(b);
    avail = _rt.host_int(avail);
    const _r = _impl.rate_format_pair_for_width(a, b, avail);
    return _rt.text_str(_r);
}

export function is_slash_command_attempt(line) {
    line = _rt.host_text(line);
    const _r = _impl.is_slash_command_attempt(line);
    return _r;
}

export function classify_command_line(line) {
    line = _rt.host_text(line);
    const _r = _impl.classify_command_line(line);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]);
}

export function parse_two_elements(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.parse_two_elements(rest);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]);
}

export function parse_with_args(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.parse_with_args(rest);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]);
}

export function split_two_positional_args(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.split_two_positional_args(rest);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]);
}

export function parse_cross_queries(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.parse_cross_queries(rest);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1])]);
}

export function slash_combine_crawl_pipe_error_segments(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.slash_combine_crawl_pipe_error_segments(rest);
    return _rt.out_option(_r, (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _v[1]]));
}

export function slash_combine_crawl_pipe_error(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.slash_combine_crawl_pipe_error(rest);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function slash_combine_crawl_operator_error_segments(rest, kind) {
    rest = _rt.host_text(rest);
    kind = _rt.host_text(kind);
    const _r = _impl.slash_combine_crawl_operator_error_segments(rest, kind);
    return _rt.out_option(_r, (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _v[1]]));
}

export function slash_combine_crawl_operator_error(rest, kind) {
    rest = _rt.host_text(rest);
    kind = _rt.host_text(kind);
    const _r = _impl.slash_combine_crawl_operator_error(rest, kind);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function slash_cross_operator_error_segments(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.slash_cross_operator_error_segments(rest);
    return _rt.out_option(_r, (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _v[1]]));
}

export function slash_cross_operator_error(rest) {
    rest = _rt.host_text(rest);
    const _r = _impl.slash_cross_operator_error(rest);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function validate_query_at_enqueue(query) {
    query = _rt.host_text(query);
    const _r = _impl.validate_query_at_enqueue(query);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function validate_command_line_segments(line) {
    line = _rt.host_text(line);
    const _r = _impl.validate_command_line_segments(line);
    return _rt.out_option(_r, (_v) => _v.map((_v) => [_rt.text_str(_v[0]), _v[1]]));
}

export function validate_command_line(line) {
    line = _rt.host_text(line);
    const _r = _impl.validate_command_line(line);
    return _rt.out_option(_r, (_v) => _rt.text_str(_v));
}

export function resolve_element_boundary(elements, name) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    name = _rt.host_text(name);
    const _r = _impl.resolve_element_boundary(elements, name);
    return [_rt.text_str(_r[0]), _rt.text_str(_r[1]), _r[2]];
}

export function get_by_name_boundary(elements, name) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    name = _rt.host_text(name);
    const _r = _impl.get_by_name_boundary(elements, name);
    return _rt.out_option(_r, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function add_element_boundary(elements, name, emoji, first) {
    const _in_elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    name = _rt.host_text(name);
    emoji = _rt.host_text(emoji);
    first = _rt.host_bool(first);
    const [_r, _new_elements] = _impl.add_element_boundary(_in_elements, name, emoji, first);
    _rt.writeback_list(elements, _new_elements, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
    return _r;
}

export function add_elements_batch_boundary(elements, items) {
    const _in_elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    items = _rt.host_list(items, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const [_r, _new_elements] = _impl.add_elements_batch_boundary(_in_elements, items);
    _rt.writeback_list(elements, _new_elements, (_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
    return _rt.int_out(_r);
}

export function trace_recipe_boundary(elements, recipes, name) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    name = _rt.host_text(name);
    const _r = _impl.trace_recipe_boundary(elements, recipes, name);
    return [_rt.int_out(_r[0]), _rt.text_str(_r[1]), _r[2].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _rt.text_str(_v[2])])];
}

export function included_element_names_boundary(recipes) {
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.included_element_names_boundary(recipes);
    return _r.map((_v) => _rt.text_str(_v));
}

export function orphan_candidates_boundary(elements, recipes) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.orphan_candidates_boundary(elements, recipes);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function export_elements_boundary(elements, recipes) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.export_elements_boundary(elements, recipes);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]);
}

export function match_elements_boundary(elements, query) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    query = _rt.host_text(query);
    const _r = _impl.match_elements_boundary(elements, query);
    return [_r[0].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]), _rt.out_option(_r[1], (_v) => _rt.text_str(_v))];
}

export function exhaust_pairs_boundary(matches, all_elements) {
    matches = _rt.host_list(matches, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    all_elements = _rt.host_list(all_elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const _r = _impl.exhaust_pairs_boundary(matches, all_elements);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function permute_pairs_boundary(matches) {
    matches = _rt.host_list(matches, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const _r = _impl.permute_pairs_boundary(matches);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function cross_pairs_boundary(left, right) {
    left = _rt.host_list(left, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    right = _rt.host_list(right, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const _r = _impl.cross_pairs_boundary(left, right);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function with_pairs_boundary(target, others) {
    target = _rt.host_tuple(target, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]);
    others = _rt.host_list(others, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    const _r = _impl.with_pairs_boundary(target, others);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function prioritize_pairs_boundary(pairs, recipes, cached) {
    pairs = _rt.host_list(pairs, (_v) => _rt.host_tuple(_v, 6, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    cached = _rt.host_list(cached, (_v) => _rt.host_text(_v));
    const _r = _impl.prioritize_pairs_boundary(pairs, recipes, cached);
    return _r.map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]);
}

export function crawl_generation_pairs_boundary(pool, tried_keys) {
    pool = _rt.host_list(pool, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    tried_keys = _rt.host_list(tried_keys, (_v) => _rt.host_text(_v));
    const _r = _impl.crawl_generation_pairs_boundary(pool, tried_keys);
    return [_r[0].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2], _rt.text_str(_v[3]), _rt.text_str(_v[4]), _v[5]]), _r[1].map((_v) => _rt.text_str(_v))];
}

export function unfilled_names_boundary(elements, recipes) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.unfilled_names_boundary(elements, recipes);
    return _r.map((_v) => _rt.text_str(_v));
}

export function ic_save_to_batches(items, recipe_refs) {
    items = _rt.host_list(items, (_v) => _rt.host_tuple(_v, 4, [(_v) => _rt.host_int(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipe_refs = _rt.host_list(recipe_refs, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v), (_v) => _rt.host_int(_v)]));
    const _r = _impl.ic_save_to_batches(items, recipe_refs);
    return [_r[0].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]), _r[1].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _rt.text_str(_v[2])])];
}

export function lineage_steps_to_batches(steps) {
    steps = _rt.host_list(steps, (_v) => _rt.host_tuple(_v, 6, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)]));
    const _r = _impl.lineage_steps_to_batches(steps);
    return [_r[0].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _v[2]]), _r[1].map((_v) => [_rt.text_str(_v[0]), _rt.text_str(_v[1]), _rt.text_str(_v[2])])];
}

export function build_export_items_boundary(elements, recipes) {
    elements = _rt.host_list(elements, (_v) => _rt.host_tuple(_v, 3, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v), (_v) => _rt.host_bool(_v)]));
    recipes = _rt.host_map(recipes, (_k) => _rt.host_text(_k), (_v) => _rt.host_list(_v, (_v) => _rt.host_tuple(_v, 2, [(_v) => _rt.host_text(_v), (_v) => _rt.host_text(_v)])));
    const _r = _impl.build_export_items_boundary(elements, recipes);
    return [_r[0].map((_v) => [_rt.int_out(_v[0]), _rt.text_str(_v[1]), _rt.text_str(_v[2]), _v[3]]), _r[1].map((_v) => [_rt.int_out(_v[0]), _rt.int_out(_v[1]), _rt.int_out(_v[2])])];
}

