// Host-facing API for regex.sudo — generated by sudoc. Traps throw
// _rt.SudoTrap; Err results throw _rt.SudoError; invalid inputs throw
// TypeError/RangeError (see _sudo_rt.mjs).
import * as _impl from "./_regex_impl.mjs";
import * as _rt from "./_sudo_rt.mjs";

export function regex_search(pattern, input, ignore_case) {
    pattern = _rt.host_text(pattern);
    input = _rt.host_text(input);
    ignore_case = _rt.host_bool(ignore_case);
    const _r = _impl.regex_search(pattern, input, ignore_case);
    return _rt.out_result(_r, (_v) => _v, (_e) => _rt.text_str(_e));
}

export function regex_is_valid(pattern) {
    pattern = _rt.host_text(pattern);
    const _r = _impl.regex_is_valid(pattern);
    return _r;
}

export function glob_match(pattern, input, ignore_case) {
    pattern = _rt.host_text(pattern);
    input = _rt.host_text(input);
    ignore_case = _rt.host_bool(ignore_case);
    const _r = _impl.glob_match(pattern, input, ignore_case);
    return _r;
}

