// GENERATED by //bookmarklet:version_mjs — do not edit, do not commit.
// The value is stamped from tools/workspace_status.sh (STABLE_VERSION), the
// same source //release:wheel uses for the Python wheel's version. There is
// deliberately no fallback: an unstamped build yields "0.0.0", which is what
// workspace_status.sh emits for a tagless/shallow checkout and what
// infinite_craft_cli/__init__.py reports when package metadata is missing.
export const TRAINER_VERSION = "STAMP_STABLE_VERSION";
